FROM nginx

# ADD myapp.conf /etc/nginx/conf.d/

RUN rm -f /usr/share/nginx/html/index.html

ADD index.html /usr/share/nginx/html/
ADD nice.gif /usr/share/nginx/html/
ADD awesome.gif /usr/share/nginx/html/